DROP TABLE IF EXISTS users;

CREATE TABLE IF NOT EXISTS users (
    user_id serial PRIMARY KEY,
	email VARCHAR (50) UNIQUE NOT NULL,
	username VARCHAR(50) UNIQUE NOT NULL,
	password VARCHAR(300) NOT NULL);